kind = "web"
previewPath = "/"
title = "Coolivate Website"
version = "1.0.0"
id = "artifacts/coolivate"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23480

[services.development]
run = "pnpm --filter @workspace/coolivate run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/coolivate", "run", "build" ]
publicDir = "artifacts/coolivate/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23480"
BASE_PATH = "/"
